/* Generated by Together */

package de.botsnscouts.server;

public interface ModusConstants {    
    int SPIELSTART=0;
    int INITAUSR=1;
    int PROGRAMMIERUNG=2;
    int POWERUP=3;
    int ENTSPERREN=4;
    int SPIELENDE=5;
    int NIX=6;
    int ALLGEMEIN=NIX;
    int ZERSTOERT_ASYNC=7;
    int ZERSTOERT_SYNC=8;
    int FRAGENERLAUBT=10;
    int KEINEFRAGEN=11;
 }

